package animal;

/**
 *
 * @author ryanl
 */
public class Animal {
   
    private String breed;
    private int lifespan;
    private String behavior;
    private double price;

    
    // getters and setters: generated by ALT + insert --> go down to getters and setters 
    public String getBreed() {
        return breed;
    }

    public void setBreed(String breed) {
        this.breed = breed;
    }

    public int getLifespan() {
        return lifespan;
    }

    public void setLifespan(int lifespan) {
        this.lifespan = lifespan;
    }

    public String getBehavior() {
        return behavior;
    }

    public void setBehavior(String behavior) {
        this.behavior = behavior;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }
    
    
}
